name = "nees"
compatibility_date = "2024-04-11"
pages_build_output_dir = "./build/client"
compatibility_flags = ["nodejs_compat"]
# kv_namespaces = [{ binding = "cache", id = "cache" }]

[vars]
UPSTASH_REDIS_REST_URL = "https://clever-magpie-34989.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "AYitAAIncDE5MjEwYTk4YTM3ZDc0OWIwYjQ1NTgyODdlYmU0NmIyY3AxMzQ5ODk"
UPSTASH_KAFKA_REST_PASSWORD = "MjZlNTExY2UtNDFkNy00M2I0LTlmMzQtZjRmNjBhN2ZlYjM4"
UPSTASH_KAFKA_REST_URL = "precious-mastodon-5433-us1-kafka.upstash.io:9092"
UPSTASH_KAFKA_REST_USERNAME = "cHJlY2lvdXMtbWFzdG9kb24tNTQzMyRazNl64ovZv_6NZAu-73hr6PgNHO6V370"
COOKIE_SESSION_SECRET = "secret"
GITHUB_CLIENT_ID = "Ov23liQlTaXkAND0Xd8I"
GITHUB_CLIENT_SECRET = "a3be63c1a5b5809afa0899d88eb4ec8fd6feab97"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "dbs"
database_id = "fc26294e-54eb-473c-9b11-9d3eae490452"
migrations_dir = "./app/drizzle/migrations"
preview_database_id = "asdff"
# database_internal_env = "DATABASE_URL"
# migrations_table = "_d1_migrations"

# [[analytics_engine_datasets]]
# binding = "counterscale"
# dataset = "metricsDataset"
