export const env = {
	UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
	UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
	// CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN,
	// CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID,
	// CLOUDFLARE_ZONE_ID: process.env.CLOUDFLARE_ZONE_ID,
};
