name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps: 
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.6.0
        # preCommands: echo "*** pre command ***"
        # postCommands: |
        #   echo "*** post commands ***"
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # workingDirectory: './'
          packageManager: 'pnpm'
          command: deploy