# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     name: Deploy
#     steps: 
#       - uses: actions/checkout@v4
#       - name: Deploy
#         uses: cloudflare/wrangler-action@v3
#         # preCommands: echo "*** pre command ***"
#         # postCommands: |
#         #   echo "*** post commands ***"
#         with:
#           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#           # workingDirectory: './'
#           wranglerVersion: "3"
#           packageManager: pnpm
#           environment: production
#           command: deploy

name: Deploy

# on:
#   workflow_run:
#     workflows: ['CI']
#     types: [completed]
#     branches: [main]
on:
  push:
    branches:
      - main

jobs:
  check:
    name: Build and deploy CF Pages
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm build

      - name: Deploy wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy
          packageManager: 'pnpm'
          wranglerVersion: '3.23.0'
